### ISSUE TITLE
UnhandledPromiseRejectionWarning: The "chunk" argument must be one of type string or Buffer. Received type object

### ISSUE THREAD

**Issue by tomferreira** [mircoc/cordova-plugin-settings-hook#14]
Since Cordova 8, the file AndroidManifest.xml moved to platforms/android/app/src/main folder.

However, the variable platformPath at method updatePlatformConfig defined the old path.
https://github.com/mircoc/cordova-plugin-settings-hook/blob/f51bc971a48f2a6476b545c4f82786251a067314/src/index.js#L253

`(node:16412) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be one of type string or Buffer. Received type object
    at validChunk (_stream_writable.js:258:10)
    at Socket.Writable.write (_stream_writable.js:292:21)
    at Socket.stream.write (C:\Users\cirillor\AppData\Roaming\npm\node_modules\cordova\node_modules\ansi\lib\newlines.js:36:21)
    at C:\Users\cirillor\Desktop\Projetos\Prayer\plugins\cordova-plugin-settings-hook\updatePlatformConfig.js:2:52336
    at Array.forEach (<anonymous>)
    at C:\Users\cirillor\Desktop\Projetos\Prayer\plugins\cordova-plugin-settings-hook\updatePlatformConfig.js:2:52185
    at t.exports (C:\Users\cirillor\Desktop\Projetos\Prayer\plugins\cordova-plugin-settings-hook\updatePlatformConfig.js:2:52349)
    at runScriptViaModuleLoader (C:\Users\cirillor\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\hooks\HooksRunner.js:188:18)
    at runScript (C:\Users\cirillor\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\hooks\HooksRunner.js:164:16)
    at C:\Users\cirillor\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\hooks\HooksRunner.js:132:20
(node:16412) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:16412) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by TylerPottsDev** [comment]
Hey, have you managed to fix this issue?
